title: Victoria Pérez
description: Spanish philologist, multiplatform developer and content specialist in the STEAM field.
url: "https://victoriaperez.me"
baseurl: ""

markdown: kramdown
permalink: pretty

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
  - README.md
